### ISSUE TITLE
USER STORY: Administrator adds expiry date to the poll

### ISSUE THREAD

**Issue by ObiOne84** [ObiOne84/practice_python#7]
In order to **automatically hide the poll** as an **administrator**, I can **pick the expiry date while publishing the poll.**

## Acceptance Criteria:
- The option should be provided as a date picker
- The option should expand when clicked on
- The poll should disappear at 11:59 PM on the target date
- The real estate of the "poll" should be reserved on the home page, and a message that says "Stay Tunded, a new poll is coming soon" should appear if no other Poll is active.
- The administrator expiry date should be at least 3 days after the current date.

## Tasks:
- [x] Update the admin module view: the poll design (HTML and CSS) to include a date picker
- [x] Update the website view: show "Stay tuned, a new poll is coming soon."
- [x] Create a JavaScript function to validate that the expiry date is at least after 3 days
- [x] Create a job to check expired Polls every day at 11:59 PM and Hide them
- [x] Update the controller function
- [x] Update unit test scripts
- [x] Test the functionality

**Comment by ObiOne84** [comment]
All tasks completed
